# Generated by Django 5.2.1 on 2025-05-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='criado_em',
            new_name='enviado_em',
        ),
        migrations.AddField(
            model_name='contato',
            name='aceie_politica',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='bairro',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='cidade',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='cpf',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='estado',
            field=models.CharField(default='N/A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='numero',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='rua',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='telefone_codigo',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='telefone_numero',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='tipo_pessoa',
            field=models.CharField(choices=[('Física', 'Pessoa Física'), ('Jurídica', 'Pessoa Jurídica')], default='F', max_length=10),
            preserve_default=False,
        ),
    ]
