# Generated by Django 5.2.1 on 2025-05-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_criado_em_contato_enviado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='aceie_politica',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='mensagem',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='telefone_codigo',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='telefone_numero',
        ),
        migrations.AddField(
            model_name='contato',
            name='aceita_politica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contato',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='telefone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
