# Generated by Django 5.2.1 on 2025-05-26 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_contato_aceie_politica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('TO', 'Tocantins'), ('PA', 'Pará'), ('MA', 'Maranhão'), ('CE', 'Ceará'), ('PI', 'Piauí'), ('BA', 'Bahia')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='contato',
            name='cep',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', 'CEP deve estar no formato 00000-000.')]),
        ),
        migrations.AlterField(
            model_name='contato',
            name='cnpj',
            field=models.CharField(blank=True, default=0, max_length=18, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$', 'CNPJ deve estar no formato 00.000.000/0000-00.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='complemento',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='cpf',
            field=models.CharField(blank=True, default=0, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF deve estar no formato 000.000.000-00.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\) \\d{5}-\\d{4}$', 'Telefone deve estar no formato (DD) 00000-0000.')]),
        ),
        migrations.AlterField(
            model_name='contato',
            name='tipo_pessoa',
            field=models.CharField(choices=[('Física', 'Pessoa Física'), ('Jurídica', 'Pessoa Jurídica')], default='Física', max_length=10),
        ),
        migrations.AddIndex(
            model_name='contato',
            index=models.Index(fields=['email'], name='core_contat_email_57b494_idx'),
        ),
        migrations.AddIndex(
            model_name='contato',
            index=models.Index(fields=['enviado_em'], name='core_contat_enviado_fbf0d2_idx'),
        ),
    ]
