# Generated by Django 5.2.1 on 2025-05-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cidade_estado_alter_contato_cep_alter_contato_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['nome']},
        ),
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together={('nome', 'estado')},
        ),
        migrations.AddField(
            model_name='cidade',
            name='is_sede',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='core.estado'),
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='longitude',
        ),
    ]
