# Generated by Django 5.2.1 on 2025-05-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cidade_options_alter_cidade_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
